# Generated by Django 3.2.13 on 2022-11-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20221119_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='id',
            new_name='actor_id',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='id',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='id',
            new_name='keyword_id',
        ),
    ]
