# Generated by Django 3.2.13 on 2022-11-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221119_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor_ids',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors_ids',
            field=models.ManyToManyField(to='movies.Actor'),
        ),
    ]
