# Generated by Django 3.2.13 on 2022-11-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20221119_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actors_ids',
            new_name='actor_ids',
        ),
    ]
